# Generated by Django 5.0.4 on 2024-05-16 15:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('text_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=20)),
                ('source', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('sizeoffile', models.ImageField(upload_to='')),
                ('filetype', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
